// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/flashcards.proto
#ifndef GRPC_proto_2fflashcards_2eproto__INCLUDED
#define GRPC_proto_2fflashcards_2eproto__INCLUDED

#include "proto/flashcards.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace flashcards {

// Service definition
class FlashcardService final {
 public:
  static constexpr char const* service_full_name() {
    return "flashcards.FlashcardService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CreateTopic(::grpc::ClientContext* context, const ::flashcards::CreateTopicRequest& request, ::flashcards::CreateTopicResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::flashcards::CreateTopicResponse>> AsyncCreateTopic(::grpc::ClientContext* context, const ::flashcards::CreateTopicRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::flashcards::CreateTopicResponse>>(AsyncCreateTopicRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::flashcards::CreateTopicResponse>> PrepareAsyncCreateTopic(::grpc::ClientContext* context, const ::flashcards::CreateTopicRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::flashcards::CreateTopicResponse>>(PrepareAsyncCreateTopicRaw(context, request, cq));
    }
    virtual ::grpc::Status ReviewComplete(::grpc::ClientContext* context, const ::flashcards::ReviewCompleteRequest& request, ::flashcards::ReviewCompleteResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::flashcards::ReviewCompleteResponse>> AsyncReviewComplete(::grpc::ClientContext* context, const ::flashcards::ReviewCompleteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::flashcards::ReviewCompleteResponse>>(AsyncReviewCompleteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::flashcards::ReviewCompleteResponse>> PrepareAsyncReviewComplete(::grpc::ClientContext* context, const ::flashcards::ReviewCompleteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::flashcards::ReviewCompleteResponse>>(PrepareAsyncReviewCompleteRaw(context, request, cq));
    }
    virtual ::grpc::Status AddCard(::grpc::ClientContext* context, const ::flashcards::AddCardRequest& request, ::flashcards::AddCardResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::flashcards::AddCardResponse>> AsyncAddCard(::grpc::ClientContext* context, const ::flashcards::AddCardRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::flashcards::AddCardResponse>>(AsyncAddCardRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::flashcards::AddCardResponse>> PrepareAsyncAddCard(::grpc::ClientContext* context, const ::flashcards::AddCardRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::flashcards::AddCardResponse>>(PrepareAsyncAddCardRaw(context, request, cq));
    }
    virtual ::grpc::Status GetDueCards(::grpc::ClientContext* context, const ::flashcards::GetDueCardsRequest& request, ::flashcards::GetDueCardsResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::flashcards::GetDueCardsResponse>> AsyncGetDueCards(::grpc::ClientContext* context, const ::flashcards::GetDueCardsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::flashcards::GetDueCardsResponse>>(AsyncGetDueCardsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::flashcards::GetDueCardsResponse>> PrepareAsyncGetDueCards(::grpc::ClientContext* context, const ::flashcards::GetDueCardsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::flashcards::GetDueCardsResponse>>(PrepareAsyncGetDueCardsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void CreateTopic(::grpc::ClientContext* context, const ::flashcards::CreateTopicRequest* request, ::flashcards::CreateTopicResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CreateTopic(::grpc::ClientContext* context, const ::flashcards::CreateTopicRequest* request, ::flashcards::CreateTopicResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ReviewComplete(::grpc::ClientContext* context, const ::flashcards::ReviewCompleteRequest* request, ::flashcards::ReviewCompleteResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReviewComplete(::grpc::ClientContext* context, const ::flashcards::ReviewCompleteRequest* request, ::flashcards::ReviewCompleteResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void AddCard(::grpc::ClientContext* context, const ::flashcards::AddCardRequest* request, ::flashcards::AddCardResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AddCard(::grpc::ClientContext* context, const ::flashcards::AddCardRequest* request, ::flashcards::AddCardResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetDueCards(::grpc::ClientContext* context, const ::flashcards::GetDueCardsRequest* request, ::flashcards::GetDueCardsResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetDueCards(::grpc::ClientContext* context, const ::flashcards::GetDueCardsRequest* request, ::flashcards::GetDueCardsResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::flashcards::CreateTopicResponse>* AsyncCreateTopicRaw(::grpc::ClientContext* context, const ::flashcards::CreateTopicRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::flashcards::CreateTopicResponse>* PrepareAsyncCreateTopicRaw(::grpc::ClientContext* context, const ::flashcards::CreateTopicRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::flashcards::ReviewCompleteResponse>* AsyncReviewCompleteRaw(::grpc::ClientContext* context, const ::flashcards::ReviewCompleteRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::flashcards::ReviewCompleteResponse>* PrepareAsyncReviewCompleteRaw(::grpc::ClientContext* context, const ::flashcards::ReviewCompleteRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::flashcards::AddCardResponse>* AsyncAddCardRaw(::grpc::ClientContext* context, const ::flashcards::AddCardRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::flashcards::AddCardResponse>* PrepareAsyncAddCardRaw(::grpc::ClientContext* context, const ::flashcards::AddCardRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::flashcards::GetDueCardsResponse>* AsyncGetDueCardsRaw(::grpc::ClientContext* context, const ::flashcards::GetDueCardsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::flashcards::GetDueCardsResponse>* PrepareAsyncGetDueCardsRaw(::grpc::ClientContext* context, const ::flashcards::GetDueCardsRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CreateTopic(::grpc::ClientContext* context, const ::flashcards::CreateTopicRequest& request, ::flashcards::CreateTopicResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::flashcards::CreateTopicResponse>> AsyncCreateTopic(::grpc::ClientContext* context, const ::flashcards::CreateTopicRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::flashcards::CreateTopicResponse>>(AsyncCreateTopicRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::flashcards::CreateTopicResponse>> PrepareAsyncCreateTopic(::grpc::ClientContext* context, const ::flashcards::CreateTopicRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::flashcards::CreateTopicResponse>>(PrepareAsyncCreateTopicRaw(context, request, cq));
    }
    ::grpc::Status ReviewComplete(::grpc::ClientContext* context, const ::flashcards::ReviewCompleteRequest& request, ::flashcards::ReviewCompleteResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::flashcards::ReviewCompleteResponse>> AsyncReviewComplete(::grpc::ClientContext* context, const ::flashcards::ReviewCompleteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::flashcards::ReviewCompleteResponse>>(AsyncReviewCompleteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::flashcards::ReviewCompleteResponse>> PrepareAsyncReviewComplete(::grpc::ClientContext* context, const ::flashcards::ReviewCompleteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::flashcards::ReviewCompleteResponse>>(PrepareAsyncReviewCompleteRaw(context, request, cq));
    }
    ::grpc::Status AddCard(::grpc::ClientContext* context, const ::flashcards::AddCardRequest& request, ::flashcards::AddCardResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::flashcards::AddCardResponse>> AsyncAddCard(::grpc::ClientContext* context, const ::flashcards::AddCardRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::flashcards::AddCardResponse>>(AsyncAddCardRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::flashcards::AddCardResponse>> PrepareAsyncAddCard(::grpc::ClientContext* context, const ::flashcards::AddCardRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::flashcards::AddCardResponse>>(PrepareAsyncAddCardRaw(context, request, cq));
    }
    ::grpc::Status GetDueCards(::grpc::ClientContext* context, const ::flashcards::GetDueCardsRequest& request, ::flashcards::GetDueCardsResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::flashcards::GetDueCardsResponse>> AsyncGetDueCards(::grpc::ClientContext* context, const ::flashcards::GetDueCardsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::flashcards::GetDueCardsResponse>>(AsyncGetDueCardsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::flashcards::GetDueCardsResponse>> PrepareAsyncGetDueCards(::grpc::ClientContext* context, const ::flashcards::GetDueCardsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::flashcards::GetDueCardsResponse>>(PrepareAsyncGetDueCardsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CreateTopic(::grpc::ClientContext* context, const ::flashcards::CreateTopicRequest* request, ::flashcards::CreateTopicResponse* response, std::function<void(::grpc::Status)>) override;
      void CreateTopic(::grpc::ClientContext* context, const ::flashcards::CreateTopicRequest* request, ::flashcards::CreateTopicResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ReviewComplete(::grpc::ClientContext* context, const ::flashcards::ReviewCompleteRequest* request, ::flashcards::ReviewCompleteResponse* response, std::function<void(::grpc::Status)>) override;
      void ReviewComplete(::grpc::ClientContext* context, const ::flashcards::ReviewCompleteRequest* request, ::flashcards::ReviewCompleteResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void AddCard(::grpc::ClientContext* context, const ::flashcards::AddCardRequest* request, ::flashcards::AddCardResponse* response, std::function<void(::grpc::Status)>) override;
      void AddCard(::grpc::ClientContext* context, const ::flashcards::AddCardRequest* request, ::flashcards::AddCardResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetDueCards(::grpc::ClientContext* context, const ::flashcards::GetDueCardsRequest* request, ::flashcards::GetDueCardsResponse* response, std::function<void(::grpc::Status)>) override;
      void GetDueCards(::grpc::ClientContext* context, const ::flashcards::GetDueCardsRequest* request, ::flashcards::GetDueCardsResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::flashcards::CreateTopicResponse>* AsyncCreateTopicRaw(::grpc::ClientContext* context, const ::flashcards::CreateTopicRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::flashcards::CreateTopicResponse>* PrepareAsyncCreateTopicRaw(::grpc::ClientContext* context, const ::flashcards::CreateTopicRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::flashcards::ReviewCompleteResponse>* AsyncReviewCompleteRaw(::grpc::ClientContext* context, const ::flashcards::ReviewCompleteRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::flashcards::ReviewCompleteResponse>* PrepareAsyncReviewCompleteRaw(::grpc::ClientContext* context, const ::flashcards::ReviewCompleteRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::flashcards::AddCardResponse>* AsyncAddCardRaw(::grpc::ClientContext* context, const ::flashcards::AddCardRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::flashcards::AddCardResponse>* PrepareAsyncAddCardRaw(::grpc::ClientContext* context, const ::flashcards::AddCardRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::flashcards::GetDueCardsResponse>* AsyncGetDueCardsRaw(::grpc::ClientContext* context, const ::flashcards::GetDueCardsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::flashcards::GetDueCardsResponse>* PrepareAsyncGetDueCardsRaw(::grpc::ClientContext* context, const ::flashcards::GetDueCardsRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CreateTopic_;
    const ::grpc::internal::RpcMethod rpcmethod_ReviewComplete_;
    const ::grpc::internal::RpcMethod rpcmethod_AddCard_;
    const ::grpc::internal::RpcMethod rpcmethod_GetDueCards_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CreateTopic(::grpc::ServerContext* context, const ::flashcards::CreateTopicRequest* request, ::flashcards::CreateTopicResponse* response);
    virtual ::grpc::Status ReviewComplete(::grpc::ServerContext* context, const ::flashcards::ReviewCompleteRequest* request, ::flashcards::ReviewCompleteResponse* response);
    virtual ::grpc::Status AddCard(::grpc::ServerContext* context, const ::flashcards::AddCardRequest* request, ::flashcards::AddCardResponse* response);
    virtual ::grpc::Status GetDueCards(::grpc::ServerContext* context, const ::flashcards::GetDueCardsRequest* request, ::flashcards::GetDueCardsResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CreateTopic : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CreateTopic() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CreateTopic() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateTopic(::grpc::ServerContext* /*context*/, const ::flashcards::CreateTopicRequest* /*request*/, ::flashcards::CreateTopicResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateTopic(::grpc::ServerContext* context, ::flashcards::CreateTopicRequest* request, ::grpc::ServerAsyncResponseWriter< ::flashcards::CreateTopicResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ReviewComplete : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReviewComplete() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ReviewComplete() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReviewComplete(::grpc::ServerContext* /*context*/, const ::flashcards::ReviewCompleteRequest* /*request*/, ::flashcards::ReviewCompleteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReviewComplete(::grpc::ServerContext* context, ::flashcards::ReviewCompleteRequest* request, ::grpc::ServerAsyncResponseWriter< ::flashcards::ReviewCompleteResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_AddCard : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AddCard() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_AddCard() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddCard(::grpc::ServerContext* /*context*/, const ::flashcards::AddCardRequest* /*request*/, ::flashcards::AddCardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddCard(::grpc::ServerContext* context, ::flashcards::AddCardRequest* request, ::grpc::ServerAsyncResponseWriter< ::flashcards::AddCardResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetDueCards : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetDueCards() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_GetDueCards() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDueCards(::grpc::ServerContext* /*context*/, const ::flashcards::GetDueCardsRequest* /*request*/, ::flashcards::GetDueCardsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetDueCards(::grpc::ServerContext* context, ::flashcards::GetDueCardsRequest* request, ::grpc::ServerAsyncResponseWriter< ::flashcards::GetDueCardsResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CreateTopic<WithAsyncMethod_ReviewComplete<WithAsyncMethod_AddCard<WithAsyncMethod_GetDueCards<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CreateTopic : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CreateTopic() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::flashcards::CreateTopicRequest, ::flashcards::CreateTopicResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::flashcards::CreateTopicRequest* request, ::flashcards::CreateTopicResponse* response) { return this->CreateTopic(context, request, response); }));}
    void SetMessageAllocatorFor_CreateTopic(
        ::grpc::MessageAllocator< ::flashcards::CreateTopicRequest, ::flashcards::CreateTopicResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::flashcards::CreateTopicRequest, ::flashcards::CreateTopicResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CreateTopic() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateTopic(::grpc::ServerContext* /*context*/, const ::flashcards::CreateTopicRequest* /*request*/, ::flashcards::CreateTopicResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateTopic(
      ::grpc::CallbackServerContext* /*context*/, const ::flashcards::CreateTopicRequest* /*request*/, ::flashcards::CreateTopicResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ReviewComplete : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReviewComplete() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::flashcards::ReviewCompleteRequest, ::flashcards::ReviewCompleteResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::flashcards::ReviewCompleteRequest* request, ::flashcards::ReviewCompleteResponse* response) { return this->ReviewComplete(context, request, response); }));}
    void SetMessageAllocatorFor_ReviewComplete(
        ::grpc::MessageAllocator< ::flashcards::ReviewCompleteRequest, ::flashcards::ReviewCompleteResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::flashcards::ReviewCompleteRequest, ::flashcards::ReviewCompleteResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ReviewComplete() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReviewComplete(::grpc::ServerContext* /*context*/, const ::flashcards::ReviewCompleteRequest* /*request*/, ::flashcards::ReviewCompleteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReviewComplete(
      ::grpc::CallbackServerContext* /*context*/, const ::flashcards::ReviewCompleteRequest* /*request*/, ::flashcards::ReviewCompleteResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_AddCard : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AddCard() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::flashcards::AddCardRequest, ::flashcards::AddCardResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::flashcards::AddCardRequest* request, ::flashcards::AddCardResponse* response) { return this->AddCard(context, request, response); }));}
    void SetMessageAllocatorFor_AddCard(
        ::grpc::MessageAllocator< ::flashcards::AddCardRequest, ::flashcards::AddCardResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::flashcards::AddCardRequest, ::flashcards::AddCardResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AddCard() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddCard(::grpc::ServerContext* /*context*/, const ::flashcards::AddCardRequest* /*request*/, ::flashcards::AddCardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddCard(
      ::grpc::CallbackServerContext* /*context*/, const ::flashcards::AddCardRequest* /*request*/, ::flashcards::AddCardResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetDueCards : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetDueCards() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::flashcards::GetDueCardsRequest, ::flashcards::GetDueCardsResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::flashcards::GetDueCardsRequest* request, ::flashcards::GetDueCardsResponse* response) { return this->GetDueCards(context, request, response); }));}
    void SetMessageAllocatorFor_GetDueCards(
        ::grpc::MessageAllocator< ::flashcards::GetDueCardsRequest, ::flashcards::GetDueCardsResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::flashcards::GetDueCardsRequest, ::flashcards::GetDueCardsResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetDueCards() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDueCards(::grpc::ServerContext* /*context*/, const ::flashcards::GetDueCardsRequest* /*request*/, ::flashcards::GetDueCardsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetDueCards(
      ::grpc::CallbackServerContext* /*context*/, const ::flashcards::GetDueCardsRequest* /*request*/, ::flashcards::GetDueCardsResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CreateTopic<WithCallbackMethod_ReviewComplete<WithCallbackMethod_AddCard<WithCallbackMethod_GetDueCards<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CreateTopic : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CreateTopic() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CreateTopic() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateTopic(::grpc::ServerContext* /*context*/, const ::flashcards::CreateTopicRequest* /*request*/, ::flashcards::CreateTopicResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ReviewComplete : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReviewComplete() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ReviewComplete() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReviewComplete(::grpc::ServerContext* /*context*/, const ::flashcards::ReviewCompleteRequest* /*request*/, ::flashcards::ReviewCompleteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_AddCard : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AddCard() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_AddCard() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddCard(::grpc::ServerContext* /*context*/, const ::flashcards::AddCardRequest* /*request*/, ::flashcards::AddCardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetDueCards : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetDueCards() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_GetDueCards() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDueCards(::grpc::ServerContext* /*context*/, const ::flashcards::GetDueCardsRequest* /*request*/, ::flashcards::GetDueCardsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CreateTopic : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CreateTopic() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CreateTopic() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateTopic(::grpc::ServerContext* /*context*/, const ::flashcards::CreateTopicRequest* /*request*/, ::flashcards::CreateTopicResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateTopic(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReviewComplete : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReviewComplete() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ReviewComplete() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReviewComplete(::grpc::ServerContext* /*context*/, const ::flashcards::ReviewCompleteRequest* /*request*/, ::flashcards::ReviewCompleteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReviewComplete(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_AddCard : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AddCard() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_AddCard() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddCard(::grpc::ServerContext* /*context*/, const ::flashcards::AddCardRequest* /*request*/, ::flashcards::AddCardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddCard(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetDueCards : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetDueCards() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_GetDueCards() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDueCards(::grpc::ServerContext* /*context*/, const ::flashcards::GetDueCardsRequest* /*request*/, ::flashcards::GetDueCardsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetDueCards(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CreateTopic : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CreateTopic() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CreateTopic(context, request, response); }));
    }
    ~WithRawCallbackMethod_CreateTopic() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateTopic(::grpc::ServerContext* /*context*/, const ::flashcards::CreateTopicRequest* /*request*/, ::flashcards::CreateTopicResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateTopic(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReviewComplete : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReviewComplete() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReviewComplete(context, request, response); }));
    }
    ~WithRawCallbackMethod_ReviewComplete() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReviewComplete(::grpc::ServerContext* /*context*/, const ::flashcards::ReviewCompleteRequest* /*request*/, ::flashcards::ReviewCompleteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReviewComplete(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AddCard : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AddCard() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AddCard(context, request, response); }));
    }
    ~WithRawCallbackMethod_AddCard() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddCard(::grpc::ServerContext* /*context*/, const ::flashcards::AddCardRequest* /*request*/, ::flashcards::AddCardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddCard(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetDueCards : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetDueCards() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetDueCards(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetDueCards() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetDueCards(::grpc::ServerContext* /*context*/, const ::flashcards::GetDueCardsRequest* /*request*/, ::flashcards::GetDueCardsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetDueCards(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CreateTopic : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CreateTopic() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::flashcards::CreateTopicRequest, ::flashcards::CreateTopicResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::flashcards::CreateTopicRequest, ::flashcards::CreateTopicResponse>* streamer) {
                       return this->StreamedCreateTopic(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CreateTopic() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CreateTopic(::grpc::ServerContext* /*context*/, const ::flashcards::CreateTopicRequest* /*request*/, ::flashcards::CreateTopicResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCreateTopic(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::flashcards::CreateTopicRequest,::flashcards::CreateTopicResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReviewComplete : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReviewComplete() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::flashcards::ReviewCompleteRequest, ::flashcards::ReviewCompleteResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::flashcards::ReviewCompleteRequest, ::flashcards::ReviewCompleteResponse>* streamer) {
                       return this->StreamedReviewComplete(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ReviewComplete() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReviewComplete(::grpc::ServerContext* /*context*/, const ::flashcards::ReviewCompleteRequest* /*request*/, ::flashcards::ReviewCompleteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReviewComplete(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::flashcards::ReviewCompleteRequest,::flashcards::ReviewCompleteResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AddCard : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AddCard() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::flashcards::AddCardRequest, ::flashcards::AddCardResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::flashcards::AddCardRequest, ::flashcards::AddCardResponse>* streamer) {
                       return this->StreamedAddCard(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AddCard() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AddCard(::grpc::ServerContext* /*context*/, const ::flashcards::AddCardRequest* /*request*/, ::flashcards::AddCardResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAddCard(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::flashcards::AddCardRequest,::flashcards::AddCardResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetDueCards : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetDueCards() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::flashcards::GetDueCardsRequest, ::flashcards::GetDueCardsResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::flashcards::GetDueCardsRequest, ::flashcards::GetDueCardsResponse>* streamer) {
                       return this->StreamedGetDueCards(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetDueCards() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetDueCards(::grpc::ServerContext* /*context*/, const ::flashcards::GetDueCardsRequest* /*request*/, ::flashcards::GetDueCardsResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetDueCards(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::flashcards::GetDueCardsRequest,::flashcards::GetDueCardsResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CreateTopic<WithStreamedUnaryMethod_ReviewComplete<WithStreamedUnaryMethod_AddCard<WithStreamedUnaryMethod_GetDueCards<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CreateTopic<WithStreamedUnaryMethod_ReviewComplete<WithStreamedUnaryMethod_AddCard<WithStreamedUnaryMethod_GetDueCards<Service > > > > StreamedService;
};

}  // namespace flashcards


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_proto_2fflashcards_2eproto__INCLUDED
