// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/flashcards.proto

#include "proto/flashcards.pb.h"
#include "proto/flashcards.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace flashcards {

static const char* FlashcardService_method_names[] = {
  "/flashcards.FlashcardService/CreateTopic",
  "/flashcards.FlashcardService/ReviewComplete",
  "/flashcards.FlashcardService/AddCard",
  "/flashcards.FlashcardService/GetDueCards",
};

std::unique_ptr< FlashcardService::Stub> FlashcardService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FlashcardService::Stub> stub(new FlashcardService::Stub(channel, options));
  return stub;
}

FlashcardService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CreateTopic_(FlashcardService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReviewComplete_(FlashcardService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_AddCard_(FlashcardService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetDueCards_(FlashcardService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status FlashcardService::Stub::CreateTopic(::grpc::ClientContext* context, const ::flashcards::CreateTopicRequest& request, ::flashcards::CreateTopicResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flashcards::CreateTopicRequest, ::flashcards::CreateTopicResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateTopic_, context, request, response);
}

void FlashcardService::Stub::async::CreateTopic(::grpc::ClientContext* context, const ::flashcards::CreateTopicRequest* request, ::flashcards::CreateTopicResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flashcards::CreateTopicRequest, ::flashcards::CreateTopicResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateTopic_, context, request, response, std::move(f));
}

void FlashcardService::Stub::async::CreateTopic(::grpc::ClientContext* context, const ::flashcards::CreateTopicRequest* request, ::flashcards::CreateTopicResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateTopic_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flashcards::CreateTopicResponse>* FlashcardService::Stub::PrepareAsyncCreateTopicRaw(::grpc::ClientContext* context, const ::flashcards::CreateTopicRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flashcards::CreateTopicResponse, ::flashcards::CreateTopicRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateTopic_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flashcards::CreateTopicResponse>* FlashcardService::Stub::AsyncCreateTopicRaw(::grpc::ClientContext* context, const ::flashcards::CreateTopicRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateTopicRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FlashcardService::Stub::ReviewComplete(::grpc::ClientContext* context, const ::flashcards::ReviewCompleteRequest& request, ::flashcards::ReviewCompleteResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flashcards::ReviewCompleteRequest, ::flashcards::ReviewCompleteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReviewComplete_, context, request, response);
}

void FlashcardService::Stub::async::ReviewComplete(::grpc::ClientContext* context, const ::flashcards::ReviewCompleteRequest* request, ::flashcards::ReviewCompleteResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flashcards::ReviewCompleteRequest, ::flashcards::ReviewCompleteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReviewComplete_, context, request, response, std::move(f));
}

void FlashcardService::Stub::async::ReviewComplete(::grpc::ClientContext* context, const ::flashcards::ReviewCompleteRequest* request, ::flashcards::ReviewCompleteResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReviewComplete_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flashcards::ReviewCompleteResponse>* FlashcardService::Stub::PrepareAsyncReviewCompleteRaw(::grpc::ClientContext* context, const ::flashcards::ReviewCompleteRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flashcards::ReviewCompleteResponse, ::flashcards::ReviewCompleteRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReviewComplete_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flashcards::ReviewCompleteResponse>* FlashcardService::Stub::AsyncReviewCompleteRaw(::grpc::ClientContext* context, const ::flashcards::ReviewCompleteRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReviewCompleteRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FlashcardService::Stub::AddCard(::grpc::ClientContext* context, const ::flashcards::AddCardRequest& request, ::flashcards::AddCardResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flashcards::AddCardRequest, ::flashcards::AddCardResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AddCard_, context, request, response);
}

void FlashcardService::Stub::async::AddCard(::grpc::ClientContext* context, const ::flashcards::AddCardRequest* request, ::flashcards::AddCardResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flashcards::AddCardRequest, ::flashcards::AddCardResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddCard_, context, request, response, std::move(f));
}

void FlashcardService::Stub::async::AddCard(::grpc::ClientContext* context, const ::flashcards::AddCardRequest* request, ::flashcards::AddCardResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddCard_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flashcards::AddCardResponse>* FlashcardService::Stub::PrepareAsyncAddCardRaw(::grpc::ClientContext* context, const ::flashcards::AddCardRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flashcards::AddCardResponse, ::flashcards::AddCardRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AddCard_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flashcards::AddCardResponse>* FlashcardService::Stub::AsyncAddCardRaw(::grpc::ClientContext* context, const ::flashcards::AddCardRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAddCardRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status FlashcardService::Stub::GetDueCards(::grpc::ClientContext* context, const ::flashcards::GetDueCardsRequest& request, ::flashcards::GetDueCardsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::flashcards::GetDueCardsRequest, ::flashcards::GetDueCardsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetDueCards_, context, request, response);
}

void FlashcardService::Stub::async::GetDueCards(::grpc::ClientContext* context, const ::flashcards::GetDueCardsRequest* request, ::flashcards::GetDueCardsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::flashcards::GetDueCardsRequest, ::flashcards::GetDueCardsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDueCards_, context, request, response, std::move(f));
}

void FlashcardService::Stub::async::GetDueCards(::grpc::ClientContext* context, const ::flashcards::GetDueCardsRequest* request, ::flashcards::GetDueCardsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDueCards_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::flashcards::GetDueCardsResponse>* FlashcardService::Stub::PrepareAsyncGetDueCardsRaw(::grpc::ClientContext* context, const ::flashcards::GetDueCardsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::flashcards::GetDueCardsResponse, ::flashcards::GetDueCardsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetDueCards_, context, request);
}

::grpc::ClientAsyncResponseReader< ::flashcards::GetDueCardsResponse>* FlashcardService::Stub::AsyncGetDueCardsRaw(::grpc::ClientContext* context, const ::flashcards::GetDueCardsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetDueCardsRaw(context, request, cq);
  result->StartCall();
  return result;
}

FlashcardService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FlashcardService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FlashcardService::Service, ::flashcards::CreateTopicRequest, ::flashcards::CreateTopicResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FlashcardService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flashcards::CreateTopicRequest* req,
             ::flashcards::CreateTopicResponse* resp) {
               return service->CreateTopic(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FlashcardService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FlashcardService::Service, ::flashcards::ReviewCompleteRequest, ::flashcards::ReviewCompleteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FlashcardService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flashcards::ReviewCompleteRequest* req,
             ::flashcards::ReviewCompleteResponse* resp) {
               return service->ReviewComplete(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FlashcardService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FlashcardService::Service, ::flashcards::AddCardRequest, ::flashcards::AddCardResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FlashcardService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flashcards::AddCardRequest* req,
             ::flashcards::AddCardResponse* resp) {
               return service->AddCard(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FlashcardService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FlashcardService::Service, ::flashcards::GetDueCardsRequest, ::flashcards::GetDueCardsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FlashcardService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::flashcards::GetDueCardsRequest* req,
             ::flashcards::GetDueCardsResponse* resp) {
               return service->GetDueCards(ctx, req, resp);
             }, this)));
}

FlashcardService::Service::~Service() {
}

::grpc::Status FlashcardService::Service::CreateTopic(::grpc::ServerContext* context, const ::flashcards::CreateTopicRequest* request, ::flashcards::CreateTopicResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FlashcardService::Service::ReviewComplete(::grpc::ServerContext* context, const ::flashcards::ReviewCompleteRequest* request, ::flashcards::ReviewCompleteResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FlashcardService::Service::AddCard(::grpc::ServerContext* context, const ::flashcards::AddCardRequest* request, ::flashcards::AddCardResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FlashcardService::Service::GetDueCards(::grpc::ServerContext* context, const ::flashcards::GetDueCardsRequest* request, ::flashcards::GetDueCardsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace flashcards
#include <grpcpp/ports_undef.inc>

