// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/flashcards.proto
// Protobuf C++ Version: 6.33.4

#ifndef proto_2fflashcards_2eproto_2epb_2eh
#define proto_2fflashcards_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_proto_2fflashcards_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fflashcards_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_proto_2fflashcards_2eproto;
}  // extern "C"
namespace flashcards {
class AddCardRequest;
struct AddCardRequestDefaultTypeInternal;
extern AddCardRequestDefaultTypeInternal _AddCardRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull AddCardRequest_class_data_;
class AddCardResponse;
struct AddCardResponseDefaultTypeInternal;
extern AddCardResponseDefaultTypeInternal _AddCardResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull AddCardResponse_class_data_;
class CreateTopicRequest;
struct CreateTopicRequestDefaultTypeInternal;
extern CreateTopicRequestDefaultTypeInternal _CreateTopicRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CreateTopicRequest_class_data_;
class CreateTopicResponse;
struct CreateTopicResponseDefaultTypeInternal;
extern CreateTopicResponseDefaultTypeInternal _CreateTopicResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CreateTopicResponse_class_data_;
class GetDueCardsRequest;
struct GetDueCardsRequestDefaultTypeInternal;
extern GetDueCardsRequestDefaultTypeInternal _GetDueCardsRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull GetDueCardsRequest_class_data_;
class GetDueCardsResponse;
struct GetDueCardsResponseDefaultTypeInternal;
extern GetDueCardsResponseDefaultTypeInternal _GetDueCardsResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull GetDueCardsResponse_class_data_;
class ReviewCompleteRequest;
struct ReviewCompleteRequestDefaultTypeInternal;
extern ReviewCompleteRequestDefaultTypeInternal _ReviewCompleteRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ReviewCompleteRequest_class_data_;
class ReviewCompleteResponse;
struct ReviewCompleteResponseDefaultTypeInternal;
extern ReviewCompleteResponseDefaultTypeInternal _ReviewCompleteResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ReviewCompleteResponse_class_data_;
}  // namespace flashcards
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace flashcards {

// ===================================================================


// -------------------------------------------------------------------

class ReviewCompleteResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:flashcards.ReviewCompleteResponse) */ {
 public:
  inline ReviewCompleteResponse() : ReviewCompleteResponse(nullptr) {}
  ~ReviewCompleteResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ReviewCompleteResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ReviewCompleteResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ReviewCompleteResponse(::google::protobuf::internal::ConstantInitialized);

  inline ReviewCompleteResponse(const ReviewCompleteResponse& from) : ReviewCompleteResponse(nullptr, from) {}
  inline ReviewCompleteResponse(ReviewCompleteResponse&& from) noexcept
      : ReviewCompleteResponse(nullptr, ::std::move(from)) {}
  inline ReviewCompleteResponse& operator=(const ReviewCompleteResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReviewCompleteResponse& operator=(ReviewCompleteResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReviewCompleteResponse& default_instance() {
    return *reinterpret_cast<const ReviewCompleteResponse*>(
        &_ReviewCompleteResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(ReviewCompleteResponse& a, ReviewCompleteResponse& b) { a.Swap(&b); }
  inline void Swap(ReviewCompleteResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReviewCompleteResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReviewCompleteResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ReviewCompleteResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ReviewCompleteResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ReviewCompleteResponse& from) { ReviewCompleteResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ReviewCompleteResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "flashcards.ReviewCompleteResponse"; }

  explicit ReviewCompleteResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ReviewCompleteResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ReviewCompleteResponse& from);
  ReviewCompleteResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ReviewCompleteResponse&& from) noexcept
      : ReviewCompleteResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNextReviewDateFieldNumber = 1,
  };
  // int32 next_review_date = 1;
  void clear_next_review_date() ;
  ::int32_t next_review_date() const;
  void set_next_review_date(::int32_t value);

  private:
  ::int32_t _internal_next_review_date() const;
  void _internal_set_next_review_date(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:flashcards.ReviewCompleteResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ReviewCompleteResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t next_review_date_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fflashcards_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ReviewCompleteResponse_class_data_;
// -------------------------------------------------------------------

class ReviewCompleteRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:flashcards.ReviewCompleteRequest) */ {
 public:
  inline ReviewCompleteRequest() : ReviewCompleteRequest(nullptr) {}
  ~ReviewCompleteRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ReviewCompleteRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ReviewCompleteRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ReviewCompleteRequest(::google::protobuf::internal::ConstantInitialized);

  inline ReviewCompleteRequest(const ReviewCompleteRequest& from) : ReviewCompleteRequest(nullptr, from) {}
  inline ReviewCompleteRequest(ReviewCompleteRequest&& from) noexcept
      : ReviewCompleteRequest(nullptr, ::std::move(from)) {}
  inline ReviewCompleteRequest& operator=(const ReviewCompleteRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReviewCompleteRequest& operator=(ReviewCompleteRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReviewCompleteRequest& default_instance() {
    return *reinterpret_cast<const ReviewCompleteRequest*>(
        &_ReviewCompleteRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(ReviewCompleteRequest& a, ReviewCompleteRequest& b) { a.Swap(&b); }
  inline void Swap(ReviewCompleteRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReviewCompleteRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReviewCompleteRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ReviewCompleteRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ReviewCompleteRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ReviewCompleteRequest& from) { ReviewCompleteRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ReviewCompleteRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "flashcards.ReviewCompleteRequest"; }

  explicit ReviewCompleteRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ReviewCompleteRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ReviewCompleteRequest& from);
  ReviewCompleteRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ReviewCompleteRequest&& from) noexcept
      : ReviewCompleteRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUserIdFieldNumber = 1,
    kCardIdFieldNumber = 2,
    kRatingFieldNumber = 3,
  };
  // int32 user_id = 1;
  void clear_user_id() ;
  ::int32_t user_id() const;
  void set_user_id(::int32_t value);

  private:
  ::int32_t _internal_user_id() const;
  void _internal_set_user_id(::int32_t value);

  public:
  // int32 card_id = 2;
  void clear_card_id() ;
  ::int32_t card_id() const;
  void set_card_id(::int32_t value);

  private:
  ::int32_t _internal_card_id() const;
  void _internal_set_card_id(::int32_t value);

  public:
  // int32 rating = 3;
  void clear_rating() ;
  ::int32_t rating() const;
  void set_rating(::int32_t value);

  private:
  ::int32_t _internal_rating() const;
  void _internal_set_rating(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:flashcards.ReviewCompleteRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ReviewCompleteRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t user_id_;
    ::int32_t card_id_;
    ::int32_t rating_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fflashcards_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ReviewCompleteRequest_class_data_;
// -------------------------------------------------------------------

class GetDueCardsResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:flashcards.GetDueCardsResponse) */ {
 public:
  inline GetDueCardsResponse() : GetDueCardsResponse(nullptr) {}
  ~GetDueCardsResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GetDueCardsResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GetDueCardsResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GetDueCardsResponse(::google::protobuf::internal::ConstantInitialized);

  inline GetDueCardsResponse(const GetDueCardsResponse& from) : GetDueCardsResponse(nullptr, from) {}
  inline GetDueCardsResponse(GetDueCardsResponse&& from) noexcept
      : GetDueCardsResponse(nullptr, ::std::move(from)) {}
  inline GetDueCardsResponse& operator=(const GetDueCardsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetDueCardsResponse& operator=(GetDueCardsResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetDueCardsResponse& default_instance() {
    return *reinterpret_cast<const GetDueCardsResponse*>(
        &_GetDueCardsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 7;
  friend void swap(GetDueCardsResponse& a, GetDueCardsResponse& b) { a.Swap(&b); }
  inline void Swap(GetDueCardsResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetDueCardsResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetDueCardsResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GetDueCardsResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GetDueCardsResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GetDueCardsResponse& from) { GetDueCardsResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GetDueCardsResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "flashcards.GetDueCardsResponse"; }

  explicit GetDueCardsResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GetDueCardsResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GetDueCardsResponse& from);
  GetDueCardsResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GetDueCardsResponse&& from) noexcept
      : GetDueCardsResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCardIdsFieldNumber = 1,
  };
  // repeated int32 card_ids = 1;
  int card_ids_size() const;
  private:
  int _internal_card_ids_size() const;

  public:
  void clear_card_ids() ;
  ::int32_t card_ids(int index) const;
  void set_card_ids(int index, ::int32_t value);
  void add_card_ids(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& card_ids() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL mutable_card_ids();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_card_ids() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL _internal_mutable_card_ids();

  public:
  // @@protoc_insertion_point(class_scope:flashcards.GetDueCardsResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const GetDueCardsResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<::int32_t> card_ids_;
    ::google::protobuf::internal::CachedSize _card_ids_cached_byte_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fflashcards_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull GetDueCardsResponse_class_data_;
// -------------------------------------------------------------------

class GetDueCardsRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:flashcards.GetDueCardsRequest) */ {
 public:
  inline GetDueCardsRequest() : GetDueCardsRequest(nullptr) {}
  ~GetDueCardsRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GetDueCardsRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GetDueCardsRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GetDueCardsRequest(::google::protobuf::internal::ConstantInitialized);

  inline GetDueCardsRequest(const GetDueCardsRequest& from) : GetDueCardsRequest(nullptr, from) {}
  inline GetDueCardsRequest(GetDueCardsRequest&& from) noexcept
      : GetDueCardsRequest(nullptr, ::std::move(from)) {}
  inline GetDueCardsRequest& operator=(const GetDueCardsRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetDueCardsRequest& operator=(GetDueCardsRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetDueCardsRequest& default_instance() {
    return *reinterpret_cast<const GetDueCardsRequest*>(
        &_GetDueCardsRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 6;
  friend void swap(GetDueCardsRequest& a, GetDueCardsRequest& b) { a.Swap(&b); }
  inline void Swap(GetDueCardsRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetDueCardsRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetDueCardsRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GetDueCardsRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GetDueCardsRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GetDueCardsRequest& from) { GetDueCardsRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GetDueCardsRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "flashcards.GetDueCardsRequest"; }

  explicit GetDueCardsRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  GetDueCardsRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const GetDueCardsRequest& from);
  GetDueCardsRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, GetDueCardsRequest&& from) noexcept
      : GetDueCardsRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUserIdFieldNumber = 1,
    kDateFieldNumber = 2,
    kTopicIdFieldNumber = 3,
  };
  // int32 user_id = 1;
  void clear_user_id() ;
  ::int32_t user_id() const;
  void set_user_id(::int32_t value);

  private:
  ::int32_t _internal_user_id() const;
  void _internal_set_user_id(::int32_t value);

  public:
  // int32 date = 2;
  void clear_date() ;
  ::int32_t date() const;
  void set_date(::int32_t value);

  private:
  ::int32_t _internal_date() const;
  void _internal_set_date(::int32_t value);

  public:
  // int32 topic_id = 3;
  void clear_topic_id() ;
  ::int32_t topic_id() const;
  void set_topic_id(::int32_t value);

  private:
  ::int32_t _internal_topic_id() const;
  void _internal_set_topic_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:flashcards.GetDueCardsRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const GetDueCardsRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t user_id_;
    ::int32_t date_;
    ::int32_t topic_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fflashcards_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull GetDueCardsRequest_class_data_;
// -------------------------------------------------------------------

class CreateTopicResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:flashcards.CreateTopicResponse) */ {
 public:
  inline CreateTopicResponse() : CreateTopicResponse(nullptr) {}
  ~CreateTopicResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CreateTopicResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CreateTopicResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CreateTopicResponse(::google::protobuf::internal::ConstantInitialized);

  inline CreateTopicResponse(const CreateTopicResponse& from) : CreateTopicResponse(nullptr, from) {}
  inline CreateTopicResponse(CreateTopicResponse&& from) noexcept
      : CreateTopicResponse(nullptr, ::std::move(from)) {}
  inline CreateTopicResponse& operator=(const CreateTopicResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline CreateTopicResponse& operator=(CreateTopicResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CreateTopicResponse& default_instance() {
    return *reinterpret_cast<const CreateTopicResponse*>(
        &_CreateTopicResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(CreateTopicResponse& a, CreateTopicResponse& b) { a.Swap(&b); }
  inline void Swap(CreateTopicResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CreateTopicResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CreateTopicResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CreateTopicResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CreateTopicResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CreateTopicResponse& from) { CreateTopicResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CreateTopicResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "flashcards.CreateTopicResponse"; }

  explicit CreateTopicResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CreateTopicResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CreateTopicResponse& from);
  CreateTopicResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CreateTopicResponse&& from) noexcept
      : CreateTopicResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSuccessFieldNumber = 1,
  };
  // bool success = 1;
  void clear_success() ;
  bool success() const;
  void set_success(bool value);

  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);

  public:
  // @@protoc_insertion_point(class_scope:flashcards.CreateTopicResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CreateTopicResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    bool success_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fflashcards_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CreateTopicResponse_class_data_;
// -------------------------------------------------------------------

class CreateTopicRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:flashcards.CreateTopicRequest) */ {
 public:
  inline CreateTopicRequest() : CreateTopicRequest(nullptr) {}
  ~CreateTopicRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CreateTopicRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CreateTopicRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CreateTopicRequest(::google::protobuf::internal::ConstantInitialized);

  inline CreateTopicRequest(const CreateTopicRequest& from) : CreateTopicRequest(nullptr, from) {}
  inline CreateTopicRequest(CreateTopicRequest&& from) noexcept
      : CreateTopicRequest(nullptr, ::std::move(from)) {}
  inline CreateTopicRequest& operator=(const CreateTopicRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline CreateTopicRequest& operator=(CreateTopicRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CreateTopicRequest& default_instance() {
    return *reinterpret_cast<const CreateTopicRequest*>(
        &_CreateTopicRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CreateTopicRequest& a, CreateTopicRequest& b) { a.Swap(&b); }
  inline void Swap(CreateTopicRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CreateTopicRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CreateTopicRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CreateTopicRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CreateTopicRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CreateTopicRequest& from) { CreateTopicRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CreateTopicRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "flashcards.CreateTopicRequest"; }

  explicit CreateTopicRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CreateTopicRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CreateTopicRequest& from);
  CreateTopicRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CreateTopicRequest&& from) noexcept
      : CreateTopicRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNameFieldNumber = 3,
    kUserIdFieldNumber = 1,
    kTopicIdFieldNumber = 2,
  };
  // string name = 3;
  void clear_name() ;
  const ::std::string& name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_name();
  void set_allocated_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_name();

  public:
  // int32 user_id = 1;
  void clear_user_id() ;
  ::int32_t user_id() const;
  void set_user_id(::int32_t value);

  private:
  ::int32_t _internal_user_id() const;
  void _internal_set_user_id(::int32_t value);

  public:
  // int32 topic_id = 2;
  void clear_topic_id() ;
  ::int32_t topic_id() const;
  void set_topic_id(::int32_t value);

  private:
  ::int32_t _internal_topic_id() const;
  void _internal_set_topic_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:flashcards.CreateTopicRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 42,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CreateTopicRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::int32_t user_id_;
    ::int32_t topic_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fflashcards_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CreateTopicRequest_class_data_;
// -------------------------------------------------------------------

class AddCardResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:flashcards.AddCardResponse) */ {
 public:
  inline AddCardResponse() : AddCardResponse(nullptr) {}
  ~AddCardResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AddCardResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AddCardResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AddCardResponse(::google::protobuf::internal::ConstantInitialized);

  inline AddCardResponse(const AddCardResponse& from) : AddCardResponse(nullptr, from) {}
  inline AddCardResponse(AddCardResponse&& from) noexcept
      : AddCardResponse(nullptr, ::std::move(from)) {}
  inline AddCardResponse& operator=(const AddCardResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddCardResponse& operator=(AddCardResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AddCardResponse& default_instance() {
    return *reinterpret_cast<const AddCardResponse*>(
        &_AddCardResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(AddCardResponse& a, AddCardResponse& b) { a.Swap(&b); }
  inline void Swap(AddCardResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddCardResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AddCardResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AddCardResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AddCardResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AddCardResponse& from) { AddCardResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AddCardResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "flashcards.AddCardResponse"; }

  explicit AddCardResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  AddCardResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const AddCardResponse& from);
  AddCardResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, AddCardResponse&& from) noexcept
      : AddCardResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSuccessFieldNumber = 1,
  };
  // bool success = 1;
  void clear_success() ;
  bool success() const;
  void set_success(bool value);

  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);

  public:
  // @@protoc_insertion_point(class_scope:flashcards.AddCardResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const AddCardResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    bool success_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fflashcards_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull AddCardResponse_class_data_;
// -------------------------------------------------------------------

class AddCardRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:flashcards.AddCardRequest) */ {
 public:
  inline AddCardRequest() : AddCardRequest(nullptr) {}
  ~AddCardRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(AddCardRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(AddCardRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR AddCardRequest(::google::protobuf::internal::ConstantInitialized);

  inline AddCardRequest(const AddCardRequest& from) : AddCardRequest(nullptr, from) {}
  inline AddCardRequest(AddCardRequest&& from) noexcept
      : AddCardRequest(nullptr, ::std::move(from)) {}
  inline AddCardRequest& operator=(const AddCardRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline AddCardRequest& operator=(AddCardRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AddCardRequest& default_instance() {
    return *reinterpret_cast<const AddCardRequest*>(
        &_AddCardRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(AddCardRequest& a, AddCardRequest& b) { a.Swap(&b); }
  inline void Swap(AddCardRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AddCardRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AddCardRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<AddCardRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AddCardRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const AddCardRequest& from) { AddCardRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(AddCardRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "flashcards.AddCardRequest"; }

  explicit AddCardRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  AddCardRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const AddCardRequest& from);
  AddCardRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, AddCardRequest&& from) noexcept
      : AddCardRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUserIdFieldNumber = 1,
    kCardIdFieldNumber = 2,
    kTopicIdFieldNumber = 3,
  };
  // int32 user_id = 1;
  void clear_user_id() ;
  ::int32_t user_id() const;
  void set_user_id(::int32_t value);

  private:
  ::int32_t _internal_user_id() const;
  void _internal_set_user_id(::int32_t value);

  public:
  // int32 card_id = 2;
  void clear_card_id() ;
  ::int32_t card_id() const;
  void set_card_id(::int32_t value);

  private:
  ::int32_t _internal_card_id() const;
  void _internal_set_card_id(::int32_t value);

  public:
  // int32 topic_id = 3;
  void clear_topic_id() ;
  ::int32_t topic_id() const;
  void set_topic_id(::int32_t value);

  private:
  ::int32_t _internal_topic_id() const;
  void _internal_set_topic_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:flashcards.AddCardRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const AddCardRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t user_id_;
    ::int32_t card_id_;
    ::int32_t topic_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fflashcards_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull AddCardRequest_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CreateTopicRequest

// int32 user_id = 1;
inline void CreateTopicRequest::clear_user_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t CreateTopicRequest::user_id() const {
  // @@protoc_insertion_point(field_get:flashcards.CreateTopicRequest.user_id)
  return _internal_user_id();
}
inline void CreateTopicRequest::set_user_id(::int32_t value) {
  _internal_set_user_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:flashcards.CreateTopicRequest.user_id)
}
inline ::int32_t CreateTopicRequest::_internal_user_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.user_id_;
}
inline void CreateTopicRequest::_internal_set_user_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_ = value;
}

// int32 topic_id = 2;
inline void CreateTopicRequest::clear_topic_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.topic_id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t CreateTopicRequest::topic_id() const {
  // @@protoc_insertion_point(field_get:flashcards.CreateTopicRequest.topic_id)
  return _internal_topic_id();
}
inline void CreateTopicRequest::set_topic_id(::int32_t value) {
  _internal_set_topic_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:flashcards.CreateTopicRequest.topic_id)
}
inline ::int32_t CreateTopicRequest::_internal_topic_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.topic_id_;
}
inline void CreateTopicRequest::_internal_set_topic_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.topic_id_ = value;
}

// string name = 3;
inline void CreateTopicRequest::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& CreateTopicRequest::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:flashcards.CreateTopicRequest.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CreateTopicRequest::set_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:flashcards.CreateTopicRequest.name)
}
inline ::std::string* PROTOBUF_NONNULL CreateTopicRequest::mutable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:flashcards.CreateTopicRequest.name)
  return _s;
}
inline const ::std::string& CreateTopicRequest::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void CreateTopicRequest::_internal_set_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CreateTopicRequest::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CreateTopicRequest::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:flashcards.CreateTopicRequest.name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void CreateTopicRequest::set_allocated_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:flashcards.CreateTopicRequest.name)
}

// -------------------------------------------------------------------

// CreateTopicResponse

// bool success = 1;
inline void CreateTopicResponse::clear_success() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline bool CreateTopicResponse::success() const {
  // @@protoc_insertion_point(field_get:flashcards.CreateTopicResponse.success)
  return _internal_success();
}
inline void CreateTopicResponse::set_success(bool value) {
  _internal_set_success(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:flashcards.CreateTopicResponse.success)
}
inline bool CreateTopicResponse::_internal_success() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.success_;
}
inline void CreateTopicResponse::_internal_set_success(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = value;
}

// -------------------------------------------------------------------

// ReviewCompleteRequest

// int32 user_id = 1;
inline void ReviewCompleteRequest::clear_user_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t ReviewCompleteRequest::user_id() const {
  // @@protoc_insertion_point(field_get:flashcards.ReviewCompleteRequest.user_id)
  return _internal_user_id();
}
inline void ReviewCompleteRequest::set_user_id(::int32_t value) {
  _internal_set_user_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:flashcards.ReviewCompleteRequest.user_id)
}
inline ::int32_t ReviewCompleteRequest::_internal_user_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.user_id_;
}
inline void ReviewCompleteRequest::_internal_set_user_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_ = value;
}

// int32 card_id = 2;
inline void ReviewCompleteRequest::clear_card_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.card_id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t ReviewCompleteRequest::card_id() const {
  // @@protoc_insertion_point(field_get:flashcards.ReviewCompleteRequest.card_id)
  return _internal_card_id();
}
inline void ReviewCompleteRequest::set_card_id(::int32_t value) {
  _internal_set_card_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:flashcards.ReviewCompleteRequest.card_id)
}
inline ::int32_t ReviewCompleteRequest::_internal_card_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.card_id_;
}
inline void ReviewCompleteRequest::_internal_set_card_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.card_id_ = value;
}

// int32 rating = 3;
inline void ReviewCompleteRequest::clear_rating() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rating_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t ReviewCompleteRequest::rating() const {
  // @@protoc_insertion_point(field_get:flashcards.ReviewCompleteRequest.rating)
  return _internal_rating();
}
inline void ReviewCompleteRequest::set_rating(::int32_t value) {
  _internal_set_rating(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:flashcards.ReviewCompleteRequest.rating)
}
inline ::int32_t ReviewCompleteRequest::_internal_rating() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rating_;
}
inline void ReviewCompleteRequest::_internal_set_rating(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rating_ = value;
}

// -------------------------------------------------------------------

// ReviewCompleteResponse

// int32 next_review_date = 1;
inline void ReviewCompleteResponse::clear_next_review_date() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.next_review_date_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t ReviewCompleteResponse::next_review_date() const {
  // @@protoc_insertion_point(field_get:flashcards.ReviewCompleteResponse.next_review_date)
  return _internal_next_review_date();
}
inline void ReviewCompleteResponse::set_next_review_date(::int32_t value) {
  _internal_set_next_review_date(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:flashcards.ReviewCompleteResponse.next_review_date)
}
inline ::int32_t ReviewCompleteResponse::_internal_next_review_date() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.next_review_date_;
}
inline void ReviewCompleteResponse::_internal_set_next_review_date(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.next_review_date_ = value;
}

// -------------------------------------------------------------------

// AddCardRequest

// int32 user_id = 1;
inline void AddCardRequest::clear_user_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t AddCardRequest::user_id() const {
  // @@protoc_insertion_point(field_get:flashcards.AddCardRequest.user_id)
  return _internal_user_id();
}
inline void AddCardRequest::set_user_id(::int32_t value) {
  _internal_set_user_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:flashcards.AddCardRequest.user_id)
}
inline ::int32_t AddCardRequest::_internal_user_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.user_id_;
}
inline void AddCardRequest::_internal_set_user_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_ = value;
}

// int32 card_id = 2;
inline void AddCardRequest::clear_card_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.card_id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t AddCardRequest::card_id() const {
  // @@protoc_insertion_point(field_get:flashcards.AddCardRequest.card_id)
  return _internal_card_id();
}
inline void AddCardRequest::set_card_id(::int32_t value) {
  _internal_set_card_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:flashcards.AddCardRequest.card_id)
}
inline ::int32_t AddCardRequest::_internal_card_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.card_id_;
}
inline void AddCardRequest::_internal_set_card_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.card_id_ = value;
}

// int32 topic_id = 3;
inline void AddCardRequest::clear_topic_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.topic_id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t AddCardRequest::topic_id() const {
  // @@protoc_insertion_point(field_get:flashcards.AddCardRequest.topic_id)
  return _internal_topic_id();
}
inline void AddCardRequest::set_topic_id(::int32_t value) {
  _internal_set_topic_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:flashcards.AddCardRequest.topic_id)
}
inline ::int32_t AddCardRequest::_internal_topic_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.topic_id_;
}
inline void AddCardRequest::_internal_set_topic_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.topic_id_ = value;
}

// -------------------------------------------------------------------

// AddCardResponse

// bool success = 1;
inline void AddCardResponse::clear_success() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline bool AddCardResponse::success() const {
  // @@protoc_insertion_point(field_get:flashcards.AddCardResponse.success)
  return _internal_success();
}
inline void AddCardResponse::set_success(bool value) {
  _internal_set_success(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:flashcards.AddCardResponse.success)
}
inline bool AddCardResponse::_internal_success() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.success_;
}
inline void AddCardResponse::_internal_set_success(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = value;
}

// -------------------------------------------------------------------

// GetDueCardsRequest

// int32 user_id = 1;
inline void GetDueCardsRequest::clear_user_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t GetDueCardsRequest::user_id() const {
  // @@protoc_insertion_point(field_get:flashcards.GetDueCardsRequest.user_id)
  return _internal_user_id();
}
inline void GetDueCardsRequest::set_user_id(::int32_t value) {
  _internal_set_user_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:flashcards.GetDueCardsRequest.user_id)
}
inline ::int32_t GetDueCardsRequest::_internal_user_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.user_id_;
}
inline void GetDueCardsRequest::_internal_set_user_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.user_id_ = value;
}

// int32 date = 2;
inline void GetDueCardsRequest::clear_date() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.date_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t GetDueCardsRequest::date() const {
  // @@protoc_insertion_point(field_get:flashcards.GetDueCardsRequest.date)
  return _internal_date();
}
inline void GetDueCardsRequest::set_date(::int32_t value) {
  _internal_set_date(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:flashcards.GetDueCardsRequest.date)
}
inline ::int32_t GetDueCardsRequest::_internal_date() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.date_;
}
inline void GetDueCardsRequest::_internal_set_date(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.date_ = value;
}

// int32 topic_id = 3;
inline void GetDueCardsRequest::clear_topic_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.topic_id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t GetDueCardsRequest::topic_id() const {
  // @@protoc_insertion_point(field_get:flashcards.GetDueCardsRequest.topic_id)
  return _internal_topic_id();
}
inline void GetDueCardsRequest::set_topic_id(::int32_t value) {
  _internal_set_topic_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:flashcards.GetDueCardsRequest.topic_id)
}
inline ::int32_t GetDueCardsRequest::_internal_topic_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.topic_id_;
}
inline void GetDueCardsRequest::_internal_set_topic_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.topic_id_ = value;
}

// -------------------------------------------------------------------

// GetDueCardsResponse

// repeated int32 card_ids = 1;
inline int GetDueCardsResponse::_internal_card_ids_size() const {
  return _internal_card_ids().size();
}
inline int GetDueCardsResponse::card_ids_size() const {
  return _internal_card_ids_size();
}
inline void GetDueCardsResponse::clear_card_ids() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.card_ids_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t GetDueCardsResponse::card_ids(int index) const {
  // @@protoc_insertion_point(field_get:flashcards.GetDueCardsResponse.card_ids)
  return _internal_card_ids().Get(index);
}
inline void GetDueCardsResponse::set_card_ids(int index, ::int32_t value) {
  _internal_mutable_card_ids()->Set(index, value);
  // @@protoc_insertion_point(field_set:flashcards.GetDueCardsResponse.card_ids)
}
inline void GetDueCardsResponse::add_card_ids(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_card_ids()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:flashcards.GetDueCardsResponse.card_ids)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& GetDueCardsResponse::card_ids() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:flashcards.GetDueCardsResponse.card_ids)
  return _internal_card_ids();
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL GetDueCardsResponse::mutable_card_ids()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:flashcards.GetDueCardsResponse.card_ids)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_card_ids();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
GetDueCardsResponse::_internal_card_ids() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.card_ids_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL
GetDueCardsResponse::_internal_mutable_card_ids() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.card_ids_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace flashcards


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // proto_2fflashcards_2eproto_2epb_2eh
