// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/flashcards.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FlashcardService_CreateTopic_FullMethodName    = "/flashcards.FlashcardService/CreateTopic"
	FlashcardService_ReviewComplete_FullMethodName = "/flashcards.FlashcardService/ReviewComplete"
	FlashcardService_AddCard_FullMethodName        = "/flashcards.FlashcardService/AddCard"
	FlashcardService_GetDueCards_FullMethodName    = "/flashcards.FlashcardService/GetDueCards"
)

// FlashcardServiceClient is the client API for FlashcardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition
type FlashcardServiceClient interface {
	CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*CreateTopicResponse, error)
	ReviewComplete(ctx context.Context, in *ReviewCompleteRequest, opts ...grpc.CallOption) (*ReviewCompleteResponse, error)
	AddCard(ctx context.Context, in *AddCardRequest, opts ...grpc.CallOption) (*AddCardResponse, error)
	GetDueCards(ctx context.Context, in *GetDueCardsRequest, opts ...grpc.CallOption) (*GetDueCardsResponse, error)
}

type flashcardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFlashcardServiceClient(cc grpc.ClientConnInterface) FlashcardServiceClient {
	return &flashcardServiceClient{cc}
}

func (c *flashcardServiceClient) CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*CreateTopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTopicResponse)
	err := c.cc.Invoke(ctx, FlashcardService_CreateTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flashcardServiceClient) ReviewComplete(ctx context.Context, in *ReviewCompleteRequest, opts ...grpc.CallOption) (*ReviewCompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewCompleteResponse)
	err := c.cc.Invoke(ctx, FlashcardService_ReviewComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flashcardServiceClient) AddCard(ctx context.Context, in *AddCardRequest, opts ...grpc.CallOption) (*AddCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddCardResponse)
	err := c.cc.Invoke(ctx, FlashcardService_AddCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flashcardServiceClient) GetDueCards(ctx context.Context, in *GetDueCardsRequest, opts ...grpc.CallOption) (*GetDueCardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDueCardsResponse)
	err := c.cc.Invoke(ctx, FlashcardService_GetDueCards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlashcardServiceServer is the server API for FlashcardService service.
// All implementations must embed UnimplementedFlashcardServiceServer
// for forward compatibility.
//
// Service definition
type FlashcardServiceServer interface {
	CreateTopic(context.Context, *CreateTopicRequest) (*CreateTopicResponse, error)
	ReviewComplete(context.Context, *ReviewCompleteRequest) (*ReviewCompleteResponse, error)
	AddCard(context.Context, *AddCardRequest) (*AddCardResponse, error)
	GetDueCards(context.Context, *GetDueCardsRequest) (*GetDueCardsResponse, error)
	mustEmbedUnimplementedFlashcardServiceServer()
}

// UnimplementedFlashcardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlashcardServiceServer struct{}

func (UnimplementedFlashcardServiceServer) CreateTopic(context.Context, *CreateTopicRequest) (*CreateTopicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTopic not implemented")
}
func (UnimplementedFlashcardServiceServer) ReviewComplete(context.Context, *ReviewCompleteRequest) (*ReviewCompleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReviewComplete not implemented")
}
func (UnimplementedFlashcardServiceServer) AddCard(context.Context, *AddCardRequest) (*AddCardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddCard not implemented")
}
func (UnimplementedFlashcardServiceServer) GetDueCards(context.Context, *GetDueCardsRequest) (*GetDueCardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDueCards not implemented")
}
func (UnimplementedFlashcardServiceServer) mustEmbedUnimplementedFlashcardServiceServer() {}
func (UnimplementedFlashcardServiceServer) testEmbeddedByValue()                          {}

// UnsafeFlashcardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlashcardServiceServer will
// result in compilation errors.
type UnsafeFlashcardServiceServer interface {
	mustEmbedUnimplementedFlashcardServiceServer()
}

func RegisterFlashcardServiceServer(s grpc.ServiceRegistrar, srv FlashcardServiceServer) {
	// If the following call panics, it indicates UnimplementedFlashcardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FlashcardService_ServiceDesc, srv)
}

func _FlashcardService_CreateTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlashcardServiceServer).CreateTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlashcardService_CreateTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlashcardServiceServer).CreateTopic(ctx, req.(*CreateTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlashcardService_ReviewComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlashcardServiceServer).ReviewComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlashcardService_ReviewComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlashcardServiceServer).ReviewComplete(ctx, req.(*ReviewCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlashcardService_AddCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlashcardServiceServer).AddCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlashcardService_AddCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlashcardServiceServer).AddCard(ctx, req.(*AddCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlashcardService_GetDueCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDueCardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlashcardServiceServer).GetDueCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FlashcardService_GetDueCards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlashcardServiceServer).GetDueCards(ctx, req.(*GetDueCardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FlashcardService_ServiceDesc is the grpc.ServiceDesc for FlashcardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FlashcardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flashcards.FlashcardService",
	HandlerType: (*FlashcardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTopic",
			Handler:    _FlashcardService_CreateTopic_Handler,
		},
		{
			MethodName: "ReviewComplete",
			Handler:    _FlashcardService_ReviewComplete_Handler,
		},
		{
			MethodName: "AddCard",
			Handler:    _FlashcardService_AddCard_Handler,
		},
		{
			MethodName: "GetDueCards",
			Handler:    _FlashcardService_GetDueCards_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/flashcards.proto",
}
