// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/flashcards.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message definitions
type CreateTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TopicId       int32                  `protobuf:"varint,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicRequest) Reset() {
	*x = CreateTopicRequest{}
	mi := &file_proto_flashcards_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest) ProtoMessage() {}

func (x *CreateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flashcards_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return file_proto_flashcards_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTopicRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateTopicRequest) GetTopicId() int32 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *CreateTopicRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicResponse) Reset() {
	*x = CreateTopicResponse{}
	mi := &file_proto_flashcards_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicResponse) ProtoMessage() {}

func (x *CreateTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flashcards_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicResponse.ProtoReflect.Descriptor instead.
func (*CreateTopicResponse) Descriptor() ([]byte, []int) {
	return file_proto_flashcards_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTopicResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ReviewCompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CardId        int32                  `protobuf:"varint,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	Rating        int32                  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewCompleteRequest) Reset() {
	*x = ReviewCompleteRequest{}
	mi := &file_proto_flashcards_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewCompleteRequest) ProtoMessage() {}

func (x *ReviewCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flashcards_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewCompleteRequest.ProtoReflect.Descriptor instead.
func (*ReviewCompleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_flashcards_proto_rawDescGZIP(), []int{2}
}

func (x *ReviewCompleteRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReviewCompleteRequest) GetCardId() int32 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *ReviewCompleteRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type ReviewCompleteResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NextReviewDate int32                  `protobuf:"varint,1,opt,name=next_review_date,json=nextReviewDate,proto3" json:"next_review_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReviewCompleteResponse) Reset() {
	*x = ReviewCompleteResponse{}
	mi := &file_proto_flashcards_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewCompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewCompleteResponse) ProtoMessage() {}

func (x *ReviewCompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flashcards_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewCompleteResponse.ProtoReflect.Descriptor instead.
func (*ReviewCompleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_flashcards_proto_rawDescGZIP(), []int{3}
}

func (x *ReviewCompleteResponse) GetNextReviewDate() int32 {
	if x != nil {
		return x.NextReviewDate
	}
	return 0
}

type AddCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CardId        int32                  `protobuf:"varint,2,opt,name=card_id,json=cardId,proto3" json:"card_id,omitempty"`
	TopicId       int32                  `protobuf:"varint,3,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCardRequest) Reset() {
	*x = AddCardRequest{}
	mi := &file_proto_flashcards_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCardRequest) ProtoMessage() {}

func (x *AddCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flashcards_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCardRequest.ProtoReflect.Descriptor instead.
func (*AddCardRequest) Descriptor() ([]byte, []int) {
	return file_proto_flashcards_proto_rawDescGZIP(), []int{4}
}

func (x *AddCardRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddCardRequest) GetCardId() int32 {
	if x != nil {
		return x.CardId
	}
	return 0
}

func (x *AddCardRequest) GetTopicId() int32 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

type AddCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCardResponse) Reset() {
	*x = AddCardResponse{}
	mi := &file_proto_flashcards_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCardResponse) ProtoMessage() {}

func (x *AddCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flashcards_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCardResponse.ProtoReflect.Descriptor instead.
func (*AddCardResponse) Descriptor() ([]byte, []int) {
	return file_proto_flashcards_proto_rawDescGZIP(), []int{5}
}

type GetDueCardsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Date          int32                  `protobuf:"varint,2,opt,name=date,proto3" json:"date,omitempty"`
	TopicId       int32                  `protobuf:"varint,3,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDueCardsRequest) Reset() {
	*x = GetDueCardsRequest{}
	mi := &file_proto_flashcards_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDueCardsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDueCardsRequest) ProtoMessage() {}

func (x *GetDueCardsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flashcards_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDueCardsRequest.ProtoReflect.Descriptor instead.
func (*GetDueCardsRequest) Descriptor() ([]byte, []int) {
	return file_proto_flashcards_proto_rawDescGZIP(), []int{6}
}

func (x *GetDueCardsRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetDueCardsRequest) GetDate() int32 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *GetDueCardsRequest) GetTopicId() int32 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

type GetDueCardsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardIds       []int32                `protobuf:"varint,1,rep,packed,name=card_ids,json=cardIds,proto3" json:"card_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDueCardsResponse) Reset() {
	*x = GetDueCardsResponse{}
	mi := &file_proto_flashcards_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDueCardsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDueCardsResponse) ProtoMessage() {}

func (x *GetDueCardsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_flashcards_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDueCardsResponse.ProtoReflect.Descriptor instead.
func (*GetDueCardsResponse) Descriptor() ([]byte, []int) {
	return file_proto_flashcards_proto_rawDescGZIP(), []int{7}
}

func (x *GetDueCardsResponse) GetCardIds() []int32 {
	if x != nil {
		return x.CardIds
	}
	return nil
}

var File_proto_flashcards_proto protoreflect.FileDescriptor

const file_proto_flashcards_proto_rawDesc = "" +
	"\n" +
	"\x16proto/flashcards.proto\x12\n" +
	"flashcards\"\\\n" +
	"\x12CreateTopicRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x19\n" +
	"\btopic_id\x18\x02 \x01(\x05R\atopicId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"/\n" +
	"\x13CreateTopicResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"a\n" +
	"\x15ReviewCompleteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x17\n" +
	"\acard_id\x18\x02 \x01(\x05R\x06cardId\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x05R\x06rating\"B\n" +
	"\x16ReviewCompleteResponse\x12(\n" +
	"\x10next_review_date\x18\x01 \x01(\x05R\x0enextReviewDate\"]\n" +
	"\x0eAddCardRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x17\n" +
	"\acard_id\x18\x02 \x01(\x05R\x06cardId\x12\x19\n" +
	"\btopic_id\x18\x03 \x01(\x05R\atopicId\"\x11\n" +
	"\x0fAddCardResponse\"\\\n" +
	"\x12GetDueCardsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\x05R\x04date\x12\x19\n" +
	"\btopic_id\x18\x03 \x01(\x05R\atopicId\"0\n" +
	"\x13GetDueCardsResponse\x12\x19\n" +
	"\bcard_ids\x18\x01 \x03(\x05R\acardIds2\xcf\x02\n" +
	"\x10FlashcardService\x12N\n" +
	"\vCreateTopic\x12\x1e.flashcards.CreateTopicRequest\x1a\x1f.flashcards.CreateTopicResponse\x12W\n" +
	"\x0eReviewComplete\x12!.flashcards.ReviewCompleteRequest\x1a\".flashcards.ReviewCompleteResponse\x12B\n" +
	"\aAddCard\x12\x1a.flashcards.AddCardRequest\x1a\x1b.flashcards.AddCardResponse\x12N\n" +
	"\vGetDueCards\x12\x1e.flashcards.GetDueCardsRequest\x1a\x1f.flashcards.GetDueCardsResponseB\x13Z\x11memcore/api/protob\x06proto3"

var (
	file_proto_flashcards_proto_rawDescOnce sync.Once
	file_proto_flashcards_proto_rawDescData []byte
)

func file_proto_flashcards_proto_rawDescGZIP() []byte {
	file_proto_flashcards_proto_rawDescOnce.Do(func() {
		file_proto_flashcards_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_flashcards_proto_rawDesc), len(file_proto_flashcards_proto_rawDesc)))
	})
	return file_proto_flashcards_proto_rawDescData
}

var file_proto_flashcards_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_flashcards_proto_goTypes = []any{
	(*CreateTopicRequest)(nil),     // 0: flashcards.CreateTopicRequest
	(*CreateTopicResponse)(nil),    // 1: flashcards.CreateTopicResponse
	(*ReviewCompleteRequest)(nil),  // 2: flashcards.ReviewCompleteRequest
	(*ReviewCompleteResponse)(nil), // 3: flashcards.ReviewCompleteResponse
	(*AddCardRequest)(nil),         // 4: flashcards.AddCardRequest
	(*AddCardResponse)(nil),        // 5: flashcards.AddCardResponse
	(*GetDueCardsRequest)(nil),     // 6: flashcards.GetDueCardsRequest
	(*GetDueCardsResponse)(nil),    // 7: flashcards.GetDueCardsResponse
}
var file_proto_flashcards_proto_depIdxs = []int32{
	0, // 0: flashcards.FlashcardService.CreateTopic:input_type -> flashcards.CreateTopicRequest
	2, // 1: flashcards.FlashcardService.ReviewComplete:input_type -> flashcards.ReviewCompleteRequest
	4, // 2: flashcards.FlashcardService.AddCard:input_type -> flashcards.AddCardRequest
	6, // 3: flashcards.FlashcardService.GetDueCards:input_type -> flashcards.GetDueCardsRequest
	1, // 4: flashcards.FlashcardService.CreateTopic:output_type -> flashcards.CreateTopicResponse
	3, // 5: flashcards.FlashcardService.ReviewComplete:output_type -> flashcards.ReviewCompleteResponse
	5, // 6: flashcards.FlashcardService.AddCard:output_type -> flashcards.AddCardResponse
	7, // 7: flashcards.FlashcardService.GetDueCards:output_type -> flashcards.GetDueCardsResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_flashcards_proto_init() }
func file_proto_flashcards_proto_init() {
	if File_proto_flashcards_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_flashcards_proto_rawDesc), len(file_proto_flashcards_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_flashcards_proto_goTypes,
		DependencyIndexes: file_proto_flashcards_proto_depIdxs,
		MessageInfos:      file_proto_flashcards_proto_msgTypes,
	}.Build()
	File_proto_flashcards_proto = out.File
	file_proto_flashcards_proto_goTypes = nil
	file_proto_flashcards_proto_depIdxs = nil
}
